var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d", 
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Seg",
            "tue": "Ter",
            "wed": "Qua",
            "thu": "Qui",
            "fri": "Sex",
            "sat": "S&aacute;b",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Abr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Set",
            "oct": "Out",
            "nov": "Nov",
            "dec": "Dez"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "All day event",
        "repeat_event": "Repeat event",
        "time": "Hora",
        "event": "Compromisso",
        "location": "Local",
        "participant": "Participantes",
        "get_data_exception": "Exception when getting data",
        "new_event": "Novo compromisso",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "Ex.: Audi&ecirc;ncia no tribunal.",
        "content": "Compromisso",
        "create_event": "Criar compromisso",
        "update_detail": "Gerenciar",
        "click_to_detail": "Ver detalhes",
        "i_delete": "Excluir", 
        "day_plural": "days",
        "others": "Outros",
        "item": ""
    }
});
